version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: 0.0.0.0
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
    networks:
      - app-network
    depends_on:
      - postgres # Убедитесь, что PostgreSQL запускается перед бэкендом
    # Можно добавить healthcheck, чтобы дождаться полной готовности PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

  telegram-bot:
    build:
      context: .
      dockerfile: ./telegram-bot/Dockerfile
    networks:
      - app-network
    depends_on:
      - postgres # Убедитесь, что PostgreSQL запускается перед ботом
    # Здесь также можно добавить healthcheck, если необходимо

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
